### PR TITLE
Add Dan Redding to maintainers list

### PR DESCRIPTION
**Pull request by binste**
@dangotbanned The vote to add you as a maintainer was positive and so following the procedure outlined in https://github.com/vega/.github?tab=readme-ov-file#adding-maintainers, this PR adds you to the official list of maintainers 🥳  Thanks again for all the hard work you put into Altair!

1. Accept the invite into the Vega Org
2. I'll add you as a reviewer of this PR
3. Check if you want to add an affiliation in this PR.
4. Feel free to merge the PR confirming that you  agree with the governance documents

In case you can't merge in this repo or in Altair, let me know! First time I'm adding someone after we've changed our governance and the access rights management.

In case you've joined the Vega slack, let me know and I'll add you to the maintainers channel. No need for this, just if you want to. Almost all conversations are happening on GitHub anyway.

### CODE REVIEW

**Review by dangotbanned — APPROVED** [review]
Thank you everyone 🎉 

I've really enjoyed contributing to `altair` and I hope to continue doing so as a maintainer. 

I agree to the terms of the Vega Org governance documents.

**Comment by arvind** [comment]
Welcome @dangotbanned!!

**Comment by dangotbanned** [comment]
> In case you can't merge in this repo or in Altair, let me know! First time I'm adding someone after we've changed our governance and the access rights management.

@binste Not able to merge, but I do approve

<details>
<summary>Screenshot</summary>

image


</details>

I was able to merge in `altair` w/ https://github.com/vega/altair/pull/3522, not sure if that helps track down the issue.

Thank you again

**Comment by binste** [comment]
> > In case you can't merge in this repo or in Altair, let me know! First time I'm adding someone after we've changed our governance and the access rights management.
> 
> @binste Not able to merge, but I do approve
> 
> Screenshot
> I was able to merge in `altair` w/ [vega/altair#3522](https://github.com/vega/altair/pull/3522), not sure if that helps track down the issue.
> 
> Thank you again

Ah that actually makes sense, sorry for the confusion! Merging in `.github` is limited to steering committee members where as other repos in the Vega org only require maintainer status.

**Review by jonmmease — APPROVED** [review]
Welcome Dan!

**Pull request merged**
